#!/usr/bin/env sh

function slice () {

	`pwd`/`dirname $0`/../Externals/pictorial/slicer.rb "`pwd`/`dirname $0`/../Resources/$1" $2 $3 $4 $5

}





slice IRTactileContinueButton.backdrop.png 20 40 20 20 
slice IRTactileContinueButton.backdrop.active.png 20 40 20 20 
slice IRTactileContinueButton.backdrop.disabled.png 20 40 20 20 

slice IRTactileNoOpButton.backdrop.png 20 20 20 20 
slice IRTactileNoOpButton.backdrop.active.png 20 20 20 20
slice IRTactileNoOpButton.backdrop.disabled.png 20 20 20 20

slice IRTactileSecondActionButton.backdrop.png 20 20 20 20 
slice IRTactileSecondActionButton.backdrop.active.png 20 20 20 20
slice IRTactileSecondActionButton.backdrop.disabled.png 20 20 20 20

slice IRTactilePreviousButton.backdrop.png 20 20 20 40
slice IRTactilePreviousButton.backdrop.active.png 20 20 20 40
slice IRTactilePreviousButton.backdrop.disabled.png 20 20 20 40

slice IRTactileDoneButton.backdrop.png 20 20 20 20 
slice IRTactileDoneButton.backdrop.active.png 20 20 20 20
slice IRTactileDoneButton.backdrop.disabled.png 20 20 20 20

slice IRBeigeBox.backdrop.png 24 24 24 24

slice IRDarkTextField.backdrop.png 12 12 12 12
slice IRDarkTextField.backdrop.active.png 12 12 12 12

