#!/usr/bin/env sh

function slice () {

	`pwd`/`dirname $0`/../Externals/pictorial/slicer.rb "`pwd`/`dirname $0`/../Resources/$1" $2 $3 $4 $5

}





slice IRTactileContinueButton.backdrop.png 20 40 20 20 
slice IRTactileContinueButton.backdrop.active.png 20 40 20 20 
slice IRTactileContinueButton.backdrop.disabled.png 20 40 20 20 

slice IRTactileNoOpButton.backdrop.png 20 20 20 20 
slice IRTactileNoOpButton.backdrop.active.png 20 20 20 20
slice IRTactileNoOpButton.backdrop.disabled.png 20 20 20 20

slice IRTactileSecondActionButton.backdrop.png 20 20 20 20 
slice IRTactileSecondActionButton.backdrop.active.png 20 20 20 20
slice IRTactileSecondActionButton.backdrop.disabled.png 20 20 20 20

slice IRTactilePreviousButton.backdrop.png 20 20 20 40
slice IRTactilePreviousButton.backdrop.active.png 20 20 20 40
slice IRTactilePreviousButton.backdrop.disabled.png 20 20 20 40

slice IRTactileDoneButton.backdrop.png 20 20 20 20 
slice IRTactileDoneButton.backdrop.active.png 20 20 20 20
slice IRTactileDoneButton.backdrop.disabled.png 20 20 20 20

slice IRBeigeBox.backdrop.png 24 24 24 24

slice IRDarkTextField.backdrop.png 12 12 12 12
slice IRDarkTextField.backdrop.active.png 12 12 12 12

slice IRCautionBox.backdrop.overlay.png 20 20 20 20
#     IRCautionBox.backdrop.stripes.png is a pattern image
slice IRCautionBox.backdrop.base.png 20 20 20 20

slice IRSkinnyScroller.dark.backdrop.vertical.png 8 0 8 0
slice IRSkinnyScroller.dark.backdrop.vertical.active.png 8 0 8 0
slice IRSkinnyScroller.light.backdrop.vertical.png 8 0 8 0
slice IRSkinnyScroller.light.backdrop.vertical.active.png 8 0 8 0

slice IRSkinnyScroller.dark.backdrop.horizontal.png  0 8 0 8
slice IRSkinnyScroller.dark.backdrop.horizontal.active.png  0 8 0 8
slice IRSkinnyScroller.light.backdrop.horizontal.png 0 8 0 8
slice IRSkinnyScroller.light.backdrop.horizontal.active.png 0 8 0 8

slice IRDarkSunkenView.backdrop.png 20 20 20 20
slice IREmperorBox.backdrop.png 0 32 0 32

slice IRIndicatorBar.backdrop.png 16 32 16 32
slice IRIndicatorBar.backdrop.active.png 16 32 16 32

slice IRBubbleBox.backdrop.png 24 96 24 24

slice IRBlueyStrip.backdrop.png 8 8 8 8

slice IRLightSlider.track.vertical.png 8 0 8 0
slice IRLightSlider.track.vertical.disabled.png 8 0 8 0

slice IRPlasticyDefaultButton.backdrop.png 8 8 8 8
slice IRPlasticyDefaultButton.backdrop.active.png 8 8 8 8
slice IRPlasticyDefaultButton.backdrop.disabled.png 8 8 8 8




